# Generated by Django 5.0.4 on 2024-04-09 09:09

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="about_me",
            field=models.TextField(default="I want to find a job"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="skills",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="skills",
            ),
        ),
    ]
