# Generated by Django 5.0.4 on 2024-04-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_jobseekerprofile_about_me_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobseekerprofile",
            options={"ordering": ("experience",)},
        ),
    ]
