# Generated by Django 5.0.4 on 2024-04-14 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'ordering': ('-first_name',)},
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='age',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(limit_value=18),
                    django.core.validators.MaxValueValidator(limit_value=100),
                ]
            ),
        ),
    ]
