# Generated by Django 5.0.4 on 2024-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_jobseekerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='email',
            field=models.CharField(default='kerelkobarabash@gmail.com', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.CharField(default='kerelkobarabash@gmail.com', max_length=60),
            preserve_default=False,
        ),
    ]
