# Generated by Django 5.0.4 on 2024-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_employerprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='allow_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
