version: "3.7"

services:
  redis_cache:
    image: redis:latest
    volumes:
      - ./data/redis/:/data
    ports:
      - "6379:6379"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./data/:/var/lib/postgres/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  message_broker:
    image: rabbitmq:latest
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/data
    ports:
      - "5672:5672"

  worker:
    build: .
    command: celery -A src.core worker -l info
    env_file:
      - .env
    volumes:
      - .:/code/
    healthcheck:
      test: ["CMD", "celery", "status"]
      interval: 10s
      retries: 5
      timeout: 5s
    depends_on:
      - message_broker
      - db
      - app

  app:
    container_name: app
    build: .
    volumes:
      - .:/code/
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi",
              "--ini", "/code/config/uwsgi/uwsgi.ini"]
    env_file:
      - .env
    depends_on:
      - db
      - message_broker
      - redis_cache

  nginx:
    container_name: nginx-1
    image: nginx:1.23.1
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
