version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/:/var/lib/postgres/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  message_broker:
    image: rabbitmq:latest
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/data
    ports:
      - "5672:5672"

  app:
    build: .
    volumes:
      - .:/code/
    command: python manage.py runserver 0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=src.core.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"
