version: "3.7"

services:
  redis_cache:
    image: redis:latest
    volumes:
      - ./data/redis/:/data
    ports:
      - "6379:6379"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./data/:/var/lib/postgres/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  message_broker:
    image: rabbitmq:latest
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/data
    ports:
      - "5672:5672"

  worker:
    build: .
    command: celery -A src.core worker -l info  # --loglevel=DEBUG
    env_file:
      - .env
    volumes:
      - .:/code/
    healthcheck:
      test: ["CMD", "celery", "status"]
      interval: 10s
      retries: 5
      timeout: 5s
    depends_on:
      - message_broker
      - db
      - app

  app:
    build: .
    volumes:
      - .:/code/
    command: python manage.py runserver 0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
      - message_broker
      - redis_cache
    ports:
      - "8000:8000"
