# Generated by Django 5.0.4 on 2024-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_jobseekerprofile_about_me_and_more"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="recalls",
            field=models.ManyToManyField(
                blank=True, related_name="recalls", to="profiles.jobseekerprofile"
            ),
        ),
    ]
