# Generated by Django 5.0.4 on 2024-04-09 09:14

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("vacancies", "0002_alter_vacancy_recalls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="required_skills",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="required_skills",
            ),
        ),
    ]
