# Generated by Django 5.0.4 on 2024-04-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_employer_vacancy_jobseekers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='jobseekers',
            new_name='interested',
        ),
    ]
