# Generated by Django 5.0.4 on 2024-04-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_vacancy_required_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="distantly",
            new_name="remote",
        ),
    ]
