# Generated by Django 5.0.4 on 2024-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_jobseekerprofile_about_me_and_more"),
        ("vacancies", "0004_rename_distantly_vacancy_remote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="recalls",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="interested",
            field=models.ManyToManyField(
                blank=True, related_name="interested_in", to="profiles.jobseekerprofile"
            ),
        ),
    ]
