# Generated by Django 5.0.4 on 2024-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'vacancies',
            '0004_rename_interested_vacancy_interested_candidates_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
