# Generated by Django 5.0.4 on 2024-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0005_remove_vacancy_recalls_vacancy_interested"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="open",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="required_experience",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
