# Generated by Django 5.0.4 on 2024-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0006_vacancy_open_vacancy_required_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="interested",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="DateTimeField, updates for every object update",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="DateTimeField, sets when object is created",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
